
```{r}
extraction_batch_source <- arrow::read_parquet(
  "../../data/processed/reference/extraction_batch_source.parquet"
)

analyte_concentration_df <- arrow::read_parquet(
  "../../data/processed/quantify-sample/analyte_concentration_no_recovery.parquet"
)
```

```{r}
analyte_peak_area <- analyte_concentration_df %>%
  dplyr::select(
    batch_number,
    cartridge_number,
    individual_native_analyte_name,
    analyte_detection_flag,
    internal_standard_name,
    internal_standard_detection_flag,
    calibration_curve_range_category,
    analyte_concentration_ng,
    limit_of_detection_concentration_ng
  )

temp_df <- analyte_peak_area %>%
  dplyr::left_join(
    extraction_batch_source,
    by = c("batch_number", "cartridge_number")
  ) %>%
  # filter down to Extraction Blanks
  dplyr::filter(stringr::str_detect(county, "Extraction Blank")) # %>%
# dplyr::mutate(
#   # run logic for alternate analyte_concentration_ng for extraction blanks
#   new_analyte_concentration_ng = dplyr::case_when(
#     (!analyte_detection_flag) ~ 0.0,
#     calibration_curve_range_category == "<LOD" ~ 0.0,
#     calibration_curve_range_category == "<LOQ" ~ (limit_of_detection_concentration_ng / (2^0.5))
#   ),
#   # merge the new value to the existing
#   analyte_concentration_ng = dplyr::if_else(
#     is.na(new_analyte_concentration_ng),
#     analyte_concentration_ng,
#     new_analyte_concentration_ng
#   )
# )
```

```{r}
temp_df %>%
  dplyr::filter(batch_number == 2) %>%
  dplyr::filter(individual_native_analyte_name == "PFOS") %>%
  dplyr::select(
    individual_native_analyte_name,
    cartridge_number,
    calibration_curve_range_category,
    analyte_concentration_ng
  )
```
