```{r}
# clear out environment
rm(list = ls())

library(magrittr)

extraction_batch_source <- arrow::read_parquet(
  "../../data/processed/reference/extraction_batch_source.parquet"
)

blank_filtered_analyte_concentration_df <- arrow::read_parquet(
  "../../data/processed/build-data-products/blank_filtered_analyte_concentration_no_recovery.parquet"
)
```

```{r}
qc_filtered_samples <- blank_filtered_analyte_concentration_df %>%
  dplyr::inner_join(
    extraction_batch_source,
    by = c("batch_number", "cartridge_number")
  ) %>%
  # filter to just QC Samples
  dplyr::filter(
    county == "Fresh Water QC" | county == "Salt Water QC"
  ) %>%
  # pull out qc level and replicate
  dplyr::mutate(
    sample_type = county,
    sample_name_length = stringr::str_length(sample_id),
    qc_replicate = stringr::str_sub(
      sample_id,
      sample_name_length,
      sample_name_length
    ),
    qc_level = stringr::str_sub(
      sample_id,
      sample_name_length - 1,
      sample_name_length - 1
    ),
    replicate_missing_flag = dplyr::if_else(
      is.na(analyte_concentration_ng),
      TRUE,
      FALSE
    )
  ) %>%
  dplyr::select(
    batch_number,
    individual_native_analyte_name,
    cartridge_number,
    sample_type,
    sample_id,
    qc_level,
    qc_replicate,
    replicate_missing_flag,
    blank_filtered_analyte_concentration_ng
  )
```

```{r}
qc_filtered_samples %>%
  dplyr::filter(batch_number == 2) %>%
  #   dplyr::filter(individual_native_analyte_name == "PFOA+P3MHpA" |
  #                   individual_native_analyte_name == "PFOS" |
  #                   individual_native_analyte_name == "PFBS" |
  #                   individual_native_analyte_name == "PFUdA") %>%
  #   # dplyr::filter(individual_native_analyte_name == "PFOA+P3MHpA") %>%
  # dplyr::filter(qc_level == "L" | qc_level == "M") %>%
  dplyr::arrange(qc_level) %>%
  dplyr::arrange(individual_native_analyte_name) %>%
  readr::write_excel_csv(
    "../../data/processed/troubleshoot/2023-05-17-quality-control-no-recovery-blank-filtered-qc.csv"
  )
```
