# Field Blank

1. Take a pool of all of the analytes for Field Blanks across all batches
2. Average them together and remove across all the batches
3. Remove the 

```{r}
library(magrittr)

extraction_batch_source <- arrow::read_parquet(
  "../../data/processed/reference/extraction_batch_source.parquet"
)

blank_filtered_analyte_concentration <- arrow::read_parquet(
  "../../data/processed/build-data-products/blank_filtered_analyte_concentration_no_recovery.parquet"
)

field_blank_averaged_analyte_concentration <- extraction_batch_source %>%
  dplyr::filter(county == "Field Blank") %>%
  dplyr::left_join(
    blank_filtered_analyte_concentration,
    by = c("batch_number", "cartridge_number")
  ) %>%
  dplyr::filter(!is.na(individual_native_analyte_name)) %>%
  dplyr::select(
    individual_native_analyte_name, blank_filtered_analyte_concentration_ng
  ) %>%
  dplyr::group_by(
    individual_native_analyte_name
  ) %>%
  dplyr::summarise(
    field_blank_average_analyte_concentration_ng = mean(blank_filtered_analyte_concentration_ng)
  )
```

```{r}
blank_filtered_analyte_concentration
```

```{r}
field_blank_averaged_analyte_concentration
```


```{r}
blank_filtered_analyte_concentration %>%
  dplyr::left_join(
    field_blank_averaged_analyte_concentration,
    by = c("individual_native_analyte_name")
  ) %>%
  dplyr::mutate(
    field_blank_blank_filtered_analyte_concentration_ng = blank_filtered_analyte_concentration_ng - field_blank_average_analyte_concentration_ng
  ) %>%
  dplyr::select(
    batch_number,
    cartridge_number,
    individual_native_analyte_name,
    field_blank_blank_filtered_analyte_concentration_ng
  )
```
