# 2023-04-27

LOD - Limit of Detection

Something coming out below LOD

## Blank Filtering Logic Change

Blank filtering, this will matter

If it is just <LOQ, can take a portion of the value

If it below LOD, we are not detecting it - represent as 0

## Where is LOD applied?

This is added in the same as min-max. This is set on the cal-curve

This would be another minimum set. LOD minimum

IF Area Ratio is below LOD

## Why use LOD?

We have values we can quantity

Values that are below quantification limit.

Could mean:
1. Not there
2. It is detected, we are confident it is there there. We are not able to quantify it.
2a. We know its not 0 but it is not a value we can confidently say.

If a value is below the level at which an instrument can detect, we are confident 0.

## Blank Filtering Logic

3 Ways to deal with range:

1. 0
2. LOD / 2
3. LOD / 2^0.5

## Configuration Files

1. Internal Standard - Max Calibration Level for a given Internal Standard
  a. internal_standard_name
  b. max calibration level

2. Bad filenames in a batch:
  a. batch_number
  b. filename
  
## How to calculate LOD (Limit of Detection)

1. Go to the Calibration Curve input and use the LOD configuration file to get the calibration average peak area ratio to get the LOD

2. Solve for concentration: 
limit_of_detection_concentration_ng = (average peak area ratio cal level - intercept)/slope

3. Logic for Handling Not within Calibration Range
   1. For instances where <LOQ, replace value with limit_of_detection_concentration_ng 
   2. For instnaces of not detected or <LOD, set to 0.0


4. Average out the 5 different extraction blanks = average_extraction_blank_concnetration_ng

5. Subtract average extraction blanks from the analyte_concentration_ng

## For non-recovery filtering

Implement same logic as with recovery for non-recovery calibration curve
