# Meeting 2023-02-21 - Data and Qunatitative Step Review

## Sep2021Calibration_Curve_source.xlsx

### Column Names

* Both
  * Sheet Names
    * Cal_1 = calibration_level
    * Sep2021 = calibration_mix

* native_analyte_concentrations
  * Col Names 
    * PDS-10000X = native_analyte_name
    * value col = native_analyte_concentration_ppt
  
* internal_standard_concentrations:
  * Col Name second table
    * internal_standard_name
    * internal_standard_concentration
    
## IS_Mix_source.xlsx

* sheet name
  * internal_standard_mix (pull out just the date)
  * column name
    * stock_mix
    * internal_standard_name
    * internal_standard_concentration_ppb
    
## Extract Batch Source

No changes necessary.

## Raw Data

* source_file_name: Not relevant to quantitative steps but useful for tracking where data is sourced from.

* Two tables
  * individual_native_analytes
  * internal_standards
  
* Split between using list of internal standards in powerpoint -> if it is in the list it is an internal standard, otherwise it is an individual_native_analyte

  * individual_native_analytes

* Columns
  * sheet_name -> individual_native_analyte
  * filename
  * individual_native_analyte_peak_area
  
  * internal_standards
  
* Columns
  * sheet_name -> internal_standard_analyte
  * filename
  * internal_standard_analyte_peak_area

Cal_2_1

Cal Samples:
	- Cal
		○ Cal Solution
	- _2 
		○ Replicate Number
	- _1
		○ Cal Level

In the absence of a replicate number - it is rep 1

If I see rep in the name, I can ignore it


Oak13_1 - _1 is the transition we are focused on. Qunatitatively, we are not looking at `_2`

If I see EPA or _3M - are not in the cal curve - All qualitative 

TODO:

- Alex: will update data documentation and code according to above feedback
- Camden: Will create a mapping file between IS and Native Analytes
- Camden: Provide corrected file for Set2

