---
title: "Processed Data"
date: 2023-02-14
output:
  html_document:
    toc: true
    toc_depth: 3
---

# Entity Relationship Diagrams

## Sourced from: Sep2021Calibration_Curve_source.xlsx

```{r}
DiagrammeR::grViz("digraph {
    //
    // Defaults
    //

    // Box for entities
    node [shape=none, margin=0]

    // One-to-many relation (from one, to many)
    edge [arrowhead=crow, arrowtail=none, dir=both]

    //
    // Entities
    //
    native_analyte_concentration [label=<
        <table border='0' cellborder='1' cellspacing='0' cellpadding='4'>
            <tr><td bgcolor='lightblue'>native_analyte_concentration</td></tr>
            // columns
            <tr><td align='left'>calibration_level: text (NOT NULL)</td></tr>
            <tr><td align='left'>calibration_mix: text (NOT NULL)</td></tr>
            <tr><td align='left'>native_analyte_name: text (NOT NULL)</td></tr>
            <tr><td align='left'>native_analyte_concentration_ppt: float (NOT NULL)</td></tr>
        </table>
    >]

    internal_standard_concentration [label=<
        <table border='0' cellborder='1' cellspacing='0' cellpadding='4'>
            <tr><td bgcolor='lightblue'>internal_standard_concentration</td></tr>
            // columns
            <tr><td align='left'>calibration_level: text (NOT NULL)</td></tr>
            <tr><td align='left'>calibration_mix: text (NOT NULL)</td></tr>
            <tr><td align='left'>internal_standard_name: text (NOT NULL)</td></tr>
            <tr><td align='left'>internal_standard_concentration_ppt: float (NOT NULL)</td></tr>
        </table>
    >]


    //
    // Relationships
    //
}
}")
```

## Sourced from: IS_Mix_source.xlsx

```{r}
DiagrammeR::grViz("digraph {
    //
    // Defaults
    //

    // Box for entities
    node [shape=none, margin=0]

    // One-to-many relation (from one, to many)
    edge [arrowhead=crow, arrowtail=none, dir=both]

    //
    // Entities
    //
    internal_standard_mix [label=<
        <table border='0' cellborder='1' cellspacing='0' cellpadding='4'>
            <tr><td bgcolor='lightblue'>internal_standard_mix</td></tr>
            // columns
            <tr><td align='left'>internal_standard_mix: text (NOT NULL)</td></tr>
            <tr><td align='left'>stock_mix: text (NOT NULL)</td></tr>
            <tr><td align='left'>internal_standard_name: text (NOT NULL)</td></tr>
            <tr><td align='left'>internal_standard_concentration_ppb: float (NOT NULL)</td></tr>
        </table>
    >]

    //
    // Relationships
    //
}
}")
```

## Sourced from: Extraction_Batches_source.xlsx

```{r}
DiagrammeR::grViz("digraph {
    //
    // Defaults
    //

    // Box for entities
    node [shape=none, margin=0]

    // One-to-many relation (from one, to many)
    edge [arrowhead=crow, arrowtail=none, dir=both]

    //
    // Entities
    //
    extract_batch_source [label=<
        <table border='0' cellborder='1' cellspacing='0' cellpadding='4'>
            <tr><td bgcolor='lightblue'>extract_batch_source</td></tr>
            // columns
            <tr><td align='left'>batch_number: text (NOT NULL)</td></tr>
            <tr><td align='left'>county: text (NOT NULL)</td></tr>
            <tr><td align='left'>sample_id: text (NOT NULL)</td></tr>
            <tr><td align='left'>cartridge_number: int (NOT NULL)</td></tr>
            <tr><td align='left'>internal_standard_used: text (NOT NULL)</td></tr>
            <tr><td align='left'>full_bottle_mass: float (NULLABLE)</td></tr>
            <tr><td align='left'>empty_bottle_mass: float (NULLABLE)</td></tr>
            <tr><td align='left'>sample_mass_g: float (NULLABLE)</td></tr>
            <tr><td align='left'>coordinates: text (NULLABLE)</td></tr>
            <tr><td align='left'>notes: text (NULLABLE)</td></tr>
        </table>
    >]

    //
    // Relationships
    //
}
}")
```


## Sourced from Set#_XXX_XXX_Short.XLS

```{r}
DiagrammeR::grViz("digraph {
    //
    // Defaults
    //

    // Box for entities
    node [shape=none, margin=0]

    // One-to-many relation (from one, to many)
    edge [arrowhead=crow, arrowtail=none, dir=both]

    //
    // Entities
    //
    sensor_data_TBD [label=<
        <table border='0' cellborder='1' cellspacing='0' cellpadding='4'>
            <tr><td bgcolor='lightblue'>sensor_data_TBD</td></tr>
            // columns
            <tr><td align='left'>internal_standard_mix: text (NOT NULL)</td></tr>
            <tr><td align='left'>stock_mix: text (NOT NULL)</td></tr>
            <tr><td align='left'>internal_standard_name: text (NOT NULL)</td></tr>
            <tr><td align='left'>internal_standard_concentration_ppb: float (NOT NULL)</td></tr>
        </table>
    >]

    //
    // Relationships
    //
}
}")
```
