```{r}
batch_filename_error <- arrow::read_parquet(
  "../../data/processed/reference/batch_filename_error.parquet"
) %>%
  # setting this to false since for filenames in this table,
  # we want to remove from the dataframe
  dplyr::mutate(
    keep_filename_flag = FALSE
  )

combined_data_df <- arrow::read_parquet(
  "../../data/processed/source/full_raw_data.parquet"
) %>%
  # join dataframe that includes error filename
  dplyr::left_join(
    batch_filename_error,
    by = c("batch_number", "filename")
  ) %>%
  # for instances where filename is null, set it to True
  # since we want to keep those filenames
  dplyr::mutate(
    keep_filename_flag = dplyr::if_else(is.na(keep_filename_flag),
      TRUE,
      keep_filename_flag
    )
  ) %>%
  dplyr::filter(keep_filename_flag)
```

```{r}
temp_analyte_df <- combined_data_df %>%
  dplyr::filter(source_type == "native_analyte") %>%
  # filter down to analytes that have a match in the reference file
  dplyr::filter(analyte_match == "Match Found") %>%
  # filter down to cal values
  dplyr::filter(
    stringr::str_detect(stringr::str_to_lower(filename), "cal")
  ) %>%
  dplyr::mutate(
    # calculate the length of the analyte name to trim the number
    # off the end
    analyte_name_length = stringr::str_length(sheet_name),
    # remove the _# from the end of the analyte name
    analyte_name = stringr::str_sub(sheet_name, 0, analyte_name_length - 2),
    # capture the transition number
    transition_number = stringr::str_sub(sheet_name, -1),
    underscore_count = stringr::str_count(filename, "_")
  ) %>%
  # only interested in the first transition for an analyte
  dplyr::filter(transition_number == 1) %>%
  # only filenames with values that are not NF
  dplyr::filter(area != "NF") %>%
  # convert area to numeric
  dplyr::mutate(
    individual_native_analyte_peak_area = as.numeric(area)
  )

without_rep_number_df <- temp_analyte_df %>%
  dplyr::filter(underscore_count == 1) %>%
  dplyr::mutate(
    replicate_number = 1,
    split_filename = stringr::str_split_fixed(filename, "_", 2),
    calibration_level = as.integer(readr::parse_number(split_filename[, 2]))
  ) %>%
  dplyr::select(
    batch_number,
    individual_native_analyte_name = analyte_name,
    replicate_number,
    calibration_level,
    individual_native_analyte_peak_area
  )

temp_df <- temp_analyte_df %>%
  dplyr::filter(batch_number == 1) %>%
  dplyr::filter(!stringr::str_detect(filename, "rep")) %>%
  dplyr::filter(!stringr::str_detect(filename, "new")) %>%
  dplyr::mutate(
    split_filename = stringr::str_split_fixed(filename, "_", 3),
    replicate_number = as.integer(readr::parse_number(split_filename[, 2])),
    calibration_level = as.integer(readr::parse_number(split_filename[, 3]))
  )
#
# dplyr::select(
#   batch_number,
#   individual_native_analyte_name = analyte_name,
#   replicate_number,
#   calibration_level,
#   individual_native_analyte_peak_area
# )
```
