```{r}
temp_df <- readr::read_csv(
  "../../data/processed/calibration-curve/calibration_curve_output_no_recov_filter.csv"
)
```

```{r}
temp_df %>%
  dplyr::filter(batch_number == 2) %>%
  dplyr::filter(individual_native_analyte_name == "PFOS") %>%
  dplyr::distinct(
    individual_native_analyte_name,
    y_intercept,
    slope
  )
```



```{r}
calibration_curve_input_df <- arrow::read_parquet(
  "../../data/processed/calibration-curve/calibration_curve_input.parquet"
)
```

```{r}
calibration_curve_input_df %>%
  dplyr::filter(batch_number == 3) %>%
  dplyr::filter(individual_native_analyte_name == "N-EtFOSA-M+NN-Me2FOSA-M") %>%
  dplyr::arrange(calibration_level)
```

```{r}
combined_data_df <- arrow::read_parquet(
  "../../data/processed/source/full_raw_data.parquet"
)
```

```{r}
combined_data_df
```


```{r}
combined_data_df %>%
  dplyr::filter(batch_number == 3) %>%
  dplyr::filter(sheet_name == "N-EtFOSA-M+NN-Me2FOSA-M_2") %>%
  dplyr::filter(stringr::str_detect(filename, "Cal")) %>%
  dplyr::filter(stringr::str_detect(filename, "9"))
```

```{r}
```
